### ISSUE TITLE
Handling ECONNRESET error

### ISSUE THREAD

**Issue by alejodiazg** [tmpvar/jsdom#1280]
im using jsdom to scrape a page, sometimes the server cuts its conecction and my application throws an ECONNRESET error that crashes my nodejs app.

this is the error

```
> node server.js

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TCP.onread (net.js:544:26)
```

my code is like this

```javascript
function ProductPage(url , callback){
	//nothing here
	config = {
		url: url,
		userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36",
		done: function(err , window){
			if(err != null){
				console.log("error at "+ url);
				console.error(err);
				queue.push(url);
				callback();
				return;
			}
                       //content

			callback();
		}
	}
	try{
		jsdom.env(config);
	}
	catch(error){
		console.log(error);
		console.log("error on this url --> " + url);
	}

}
```

As you can see i tried catching the error by wrapping the jsdom.env() call in a try but this doenst seems to fix the issue, other thing is that this way the if(err != null) never gets executed cause the error is happening before it gets to that code.

I can prevent my app from crashing by declaring a document.on("error"), but this way I cannot fix my error properly

**Comment by domenic** [comment]
Hey, just want to acknowledge this is definitely a bug in jsdom; we should be catching any such errors and forwarding them to you. I'm on vacation + conferences + work meetings until the 23rd, but hopefully will have time to look at this between events, or maybe one of the other contributors can get to it.

If you or someone else could produce a way to make a Node.js server that always triggers ECONNRESET, that would be very helpful, so that we can have a reproducible test case to add to the test suite.

**Comment by alejodiazg** [comment]
thanks for the answer

ill try to have some code that always triggers the error, 

in this case the error happens always but not always in the same page, and for some reason the error is worst (it crashes my program) when im using async.queue to control how many jsdom calls im doing, if i dont use async the error appears to be handled more gracefully and ill try to have an example of this too.

**Comment by thorn0** [comment]
It's a known bug in Node, not in jsdom: https://github.com/nodejs/node/issues/3595

**Comment by thorn0** [comment]
nodejs/node#3595 has been fixed, so this issue can be closed too.

**Comment by domenic** [comment]
Hmm awesome. @alejodiazg let us know if you are still getting the problem with the latest Node.js. @thorn0 thanks for letting us know about the real problem.

**Comment by pwdonald** [comment]
This seems to be happening again.

node: 4.3.1
jsdom: 8.1.0

**Comment by Sebmaster** [comment]
@pwdonald The node bugfix is only in 4.4.0, so you'll have to upgrade if it is indeed the node bug.

**Comment by desktoping** [comment]
```
/Users/redensanchez/blsearch/node_modules/jsdom/node_modules/request/request.js:83
    socket._httpMessage.emit('error', error)
                       ^

TypeError: Cannot read property 'emit' of null
    at Socket.connectionErrorHandler (/Users/redensanchez/blsearch/node_modules/jsdom/node_modules/request/request.js:83:24)
    at Socket.g (events.js:273:16)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1249:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! blsearch@1.0.0 start: `node --harmony index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blsearch@1.0.0 start script 'node --harmony index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the blsearch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs blsearch
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls blsearch
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/redensanchez/blsearch/npm-debug.log
```

used jsdom to loop into pages and crashes around ~10mn mark.

**Comment by aggied** [comment]
Same here. Tried both node 4.4.0 and node 6.2.0. Spent hours on this, and I just simply can't get the app to keep running to pull down even 100 pages without failing. 

`````
TypeError: Cannot read property 'emit' of null,     
at Socket.connectionErrorHandler (/home/ubuntu/pullApp/node_modules/request/request.js:83:24),     
at Socket.g (events.js:286:16),     
at emitOne (events.js:101:20),     
at Socket.emit (events.js:188:7),     
at emitErrorNT (net.js:1272:8),     
at _combinedTickCallback (internal/process/next_tick.js:74:11),     
at process._tickCallback (internal/process/next_tick.js:98:9)
`````

**Comment by thorn0** [comment]
@aggied  The current issue has been fixed. Your (and @desktoping's) exception is something else. Please submit a new issue with a detailed explanation.

**Comment by sungmoonc** [comment]
My Node version is 4.4.3 (running on Mac), but I am still getting the same error messages. It doesn't happen all the time, but only occasionally.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:552:26)
```

Server code is super simple.

```
var server = app.listen(3000, function() {
	console.log('listening on port %d', server.address().port);
});
```

**Comment by vdineva** [comment]
@sungmoonc I was getting the same error as you. My node version is 6.3.1 (running on Mac)
I was using jQuery, but when I removed is as a script to be included and started using vanilla javascript to access the DOM, I no longer get the error. Hope this helps you 
`
jsdom.env(
  "https://google.com",
  function (err, window) {
    console.log(document.querySelectorAll('a')[0].innerText)
  }
);
`
